# AN OVERVIEW OF THE NUMPY.RANDOM PACKAGE IN PYTHON

***

## INTRODUCTION

This notebook contains a detail overview of the *numpy.random* package in python. It will be explained how to use of the package, but will also include detailed explanations of some of the distributions provided for in the package.

## NUMPY

NumPy stands for Numerical Python and it is a core scientific computing library in Python. [1]. It is a provision for huge, multi-dimensional arrays and matrices, alongside an extra-large collection of high-level mathematical functions to work on these arrays.[2] It was created in 2005 by Travis Oliphant. It is an open source project, and the source code for NumPy is located at this github repository https://github.com/numpy/numpy. [3] 

### INSTALLATION

There are multiple ways to have *NumPy* library installed on your system, but the easiest way is to use a python distribution that already has NumPy installed - e.g. Anaconda. (https://docs.anaconda.com/anaconda/install/index.html)

### IMPORT

Numpy library is imported same as any other python library, using *import* command at the start of the program. Numpy is usually imported using *np* alias, which is used later in the program when reffering to the package.

In [1]:
import numpy as np

## NUMPY.RANDOM

The *random* is a module present in the NumPy library. This module contains the functions which are used for generating random numbers. [4] Random number does not mean a different number every time. Random means something that can not be predicted logically. [6] *Random* module is based on pseudo-random number generation that means it is a mathematical way that generates a sequence of nearly random numbers. It is a combination of a bit generator and a generator. In Python, the random values are produced by the generator and originate in a Bit generator.[5]

```
numpy.random.default_rng()
```
Construct a new Generator with the default BitGenerator

### SIMPLE RANDOM DATA

- [**integers**](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html#numpy.random.Generator.integers) (low[, high, size, dtype, endpoint]) 
*Return random integers from low (inclusive) to high (exclusive), or if endpoint=True, low (inclusive) to high (inclusive).*


In [21]:
rng = np.random.default_rng()

In [3]:
rng.integers(5, 10, size= (2, 10) , endpoint = True)

array([[10,  6,  6,  5,  9,  9,  9,  5,  9,  5],
       [ 5,  6,  9, 10,  7,  8, 10,  5,  8,  7]], dtype=int64)

- [**random**](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random)([size, dtype, out])
*Return random floats in the half-open interval [0.0, 1.0).*

In [8]:
rng.random(5)

array([0.09235266, 0.92908964, 0.3826136 , 0.81022262, 0.41133858])

- (b - a) * random() + a     
Random number between a and b

In [20]:
(10-5)* rng.random() + 5

5.805269109050045

- [**choice**](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.choice.html#numpy.random.Generator.choice) (a[, size, replace, p, axis, shuffle])

*Generates a random sample from a given array*

In [27]:
rng.choice(5, 3)

array([0, 3, 3], dtype=int64)

- [**bytes**](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.bytes.html#numpy.random.Generator.bytes) (length)

*Return random bytes.*

In [26]:
rng.bytes(10)

b'\xf8\x87Q\xb4.\xfb\x16\xabF\xd8'

### PERMUTATIONS

### DISTRIBUTIONS

#### Distribution 1 

#### Distribution 2

#### Distribution 3

#### Distribution 4

#### Distribution 5

### SEEDS

## CONCLUSION
***

## REFERENCES

- [1] https://towardsdatascience.com/getting-started-with-numpy-59b22df56729
- [2] https://python.plainenglish.io/what-are-basics-of-numpy-2afa9a9455cb
- [3] https://www.w3schools.com/python/numpy/numpy_intro.asp
- [4] https://www.javatpoint.com/numpy-random
- [5] https://pythonguides.com/python-numpy-random/
- [6] https://www.w3schools.com/python/numpy/numpy_random.asp

## Links to check

- https://numpy.org/doc/stable/reference/random/index.html
- https://www.w3schools.com/python/numpy/numpy_random.asp
- https://www.geeksforgeeks.org/random-sampling-in-numpy-random-function/
- https://www.javatpoint.com/numpy-random
- https://pythonguides.com/python-numpy-random/
- https://docs.scipy.org/doc/numpy-1.17.0/reference/random/generator.html